import type { AnalysisResult } from "../types/index.js";
import {
  mdHeading,
  mdTable,
  mdList,
  mdLink,
  mdBold,
  mdItalic,
} from "./markdown.js";

export function generateOverview(analysis: AnalysisResult): string {
  const sections: string[] = [];

  // Title
  sections.push(mdHeading(1, "Project Overview"));
  sections.push("");
  sections.push(
    `${mdItalic("Generated by clarity-tool")} — ${analysis.timestamp}`
  );
  sections.push("");

  // Stats
  sections.push(mdHeading(2, "Project Stats"));
  sections.push("");
  const totalModules = analysis.modules.length;
  const totalExports = analysis.modules.reduce(
    (sum, m) => sum + m.exports.length,
    0
  );
  const complexities = analysis.modules.flatMap((m) =>
    m.exports
      .filter((e) => e.complexity !== null)
      .map((e) => e.complexity!.cyclomatic)
  );
  const avgComplexity =
    complexities.length > 0
      ? (complexities.reduce((a, b) => a + b, 0) / complexities.length).toFixed(
          1
        )
      : "N/A";

  sections.push(
    mdTable(
      ["Metric", "Value"],
      [
        ["Total Modules", String(totalModules)],
        ["Total Exports", String(totalExports)],
        ["Avg Complexity", String(avgComplexity)],
      ]
    )
  );
  sections.push("");

  // Health indicators
  sections.push(mdHeading(2, "Health Indicators"));
  sections.push("");

  const documented = analysis.modules.flatMap((m) => m.exports);
  const totalExportCount = documented.length;
  const documentedCount = documented.filter((e) => e.jsdoc !== null).length;
  const complexCount = documented.filter(
    (e) => e.complexity?.isComplex
  ).length;
  const staleModules = analysis.modules.filter(
    (m) => m.gitHistory && m.gitHistory.daysSinceLastChange > 180
  );
  const pctDocumented =
    totalExportCount > 0
      ? ((documentedCount / totalExportCount) * 100).toFixed(0)
      : "0";
  const pctComplex =
    totalExportCount > 0
      ? ((complexCount / totalExportCount) * 100).toFixed(0)
      : "0";
  const pctStale =
    totalModules > 0
      ? ((staleModules.length / totalModules) * 100).toFixed(0)
      : "0";

  sections.push(
    mdTable(
      ["Indicator", "Value"],
      [
        ["Documented", `${pctDocumented}%`],
        ["Complex", `${pctComplex}%`],
        ["Stale (>180 days)", `${pctStale}%`],
      ]
    )
  );
  sections.push("");

  // Module map
  sections.push(mdHeading(2, "Module Map"));
  sections.push("");
  const moduleItems = analysis.modules.map((m) => {
    const exportCount = m.exports.length;
    const link = mdLink(m.name, `modules/${m.name}.md`);
    return `${link} — ${exportCount} export${exportCount !== 1 ? "s" : ""}`;
  });
  sections.push(mdList(moduleItems));
  sections.push("");

  // Dependency summary
  sections.push(mdHeading(2, "Dependency Summary"));
  sections.push("");
  const depEntries = Object.entries(analysis.dependencyGraph);
  if (depEntries.length === 0) {
    sections.push("No internal dependencies detected.");
  } else {
    const depRows = depEntries.map(([source, targets]) => [
      mdBold(source),
      targets.join(", ") || "—",
    ]);
    sections.push(mdTable(["Module", "Depends On"], depRows));
  }
  sections.push("");

  // Recent git activity
  sections.push(mdHeading(2, "Recent Activity"));
  sections.push("");
  const allCommits = analysis.modules
    .filter((m) => m.gitHistory)
    .flatMap((m) =>
      m.gitHistory!.commits.map((c) => ({
        ...c,
        moduleName: m.name,
      }))
    )
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
    .slice(0, 5);

  if (allCommits.length === 0) {
    sections.push("No git history available.");
  } else {
    const commitRows = allCommits.map((c) => [
      c.moduleName,
      c.hash.slice(0, 7),
      c.author,
      c.message,
      c.date,
    ]);
    sections.push(
      mdTable(["Module", "Commit", "Author", "Message", "Date"], commitRows)
    );
  }
  sections.push("");

  return sections.join("\n");
}
